// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

package com.doodod.staffmanagement.message;

public final class Company {
  private Company() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code doododmsg.UserType}
   */
  public enum UserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PASSENGER = 0;</code>
     */
    PASSENGER(0, 0),
    /**
     * <code>EMPLOYEE = 1;</code>
     */
    EMPLOYEE(1, 1),
    /**
     * <code>MACHINE = 2;</code>
     */
    MACHINE(2, 2),
    /**
     * <code>OUTDOOR = 3;</code>
     */
    OUTDOOR(3, 3),
    ;

    /**
     * <code>PASSENGER = 0;</code>
     */
    public static final int PASSENGER_VALUE = 0;
    /**
     * <code>EMPLOYEE = 1;</code>
     */
    public static final int EMPLOYEE_VALUE = 1;
    /**
     * <code>MACHINE = 2;</code>
     */
    public static final int MACHINE_VALUE = 2;
    /**
     * <code>OUTDOOR = 3;</code>
     */
    public static final int OUTDOOR_VALUE = 3;


    public final int getNumber() { return value; }

    public static UserType valueOf(int value) {
      switch (value) {
        case 0: return PASSENGER;
        case 1: return EMPLOYEE;
        case 2: return MACHINE;
        case 3: return OUTDOOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.doodod.staffmanagement.message.Company.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserType[] VALUES = values();

    public static UserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private UserType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:doododmsg.UserType)
  }

  public interface EmployeeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes phone_mac = 1;
    /**
     * <code>optional bytes phone_mac = 1;</code>
     *
     * <pre>
     * 员工手机mac地址
     * </pre>
     */
    boolean hasPhoneMac();
    /**
     * <code>optional bytes phone_mac = 1;</code>
     *
     * <pre>
     * 员工手机mac地址
     * </pre>
     */
    com.google.protobuf.ByteString getPhoneMac();

    // repeated .doododmsg.Location location = 2;
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    java.util.List<com.doodod.staffmanagement.message.Company.Location> 
        getLocationList();
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    com.doodod.staffmanagement.message.Company.Location getLocation(int index);
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    int getLocationCount();
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    java.util.List<? extends com.doodod.staffmanagement.message.Company.LocationOrBuilder> 
        getLocationOrBuilderList();
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    com.doodod.staffmanagement.message.Company.LocationOrBuilder getLocationOrBuilder(
        int index);

    // optional .doododmsg.UserType user_type = 3;
    /**
     * <code>optional .doododmsg.UserType user_type = 3;</code>
     *
     * <pre>
     * 员工类型  
     * </pre>
     */
    boolean hasUserType();
    /**
     * <code>optional .doododmsg.UserType user_type = 3;</code>
     *
     * <pre>
     * 员工类型  
     * </pre>
     */
    com.doodod.staffmanagement.message.Company.UserType getUserType();

    // optional bytes company = 4;
    /**
     * <code>optional bytes company = 4;</code>
     *
     * <pre>
     * 员工公司
     * </pre>
     */
    boolean hasCompany();
    /**
     * <code>optional bytes company = 4;</code>
     *
     * <pre>
     * 员工公司
     * </pre>
     */
    com.google.protobuf.ByteString getCompany();
  }
  /**
   * Protobuf type {@code doododmsg.Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessage
      implements EmployeeOrBuilder {
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Employee(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Employee defaultInstance;
    public static Employee getDefaultInstance() {
      return defaultInstance;
    }

    public Employee getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              phoneMac_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                location_ = new java.util.ArrayList<com.doodod.staffmanagement.message.Company.Location>();
                mutable_bitField0_ |= 0x00000002;
              }
              location_.add(input.readMessage(com.doodod.staffmanagement.message.Company.Location.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.doodod.staffmanagement.message.Company.UserType value = com.doodod.staffmanagement.message.Company.UserType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                userType_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              company_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          location_ = java.util.Collections.unmodifiableList(location_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.doodod.staffmanagement.message.Company.Employee.class, com.doodod.staffmanagement.message.Company.Employee.Builder.class);
    }

    public static com.google.protobuf.Parser<Employee> PARSER =
        new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes phone_mac = 1;
    public static final int PHONE_MAC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString phoneMac_;
    /**
     * <code>optional bytes phone_mac = 1;</code>
     *
     * <pre>
     * 员工手机mac地址
     * </pre>
     */
    public boolean hasPhoneMac() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes phone_mac = 1;</code>
     *
     * <pre>
     * 员工手机mac地址
     * </pre>
     */
    public com.google.protobuf.ByteString getPhoneMac() {
      return phoneMac_;
    }

    // repeated .doododmsg.Location location = 2;
    public static final int LOCATION_FIELD_NUMBER = 2;
    private java.util.List<com.doodod.staffmanagement.message.Company.Location> location_;
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    public java.util.List<com.doodod.staffmanagement.message.Company.Location> getLocationList() {
      return location_;
    }
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    public java.util.List<? extends com.doodod.staffmanagement.message.Company.LocationOrBuilder> 
        getLocationOrBuilderList() {
      return location_;
    }
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    public int getLocationCount() {
      return location_.size();
    }
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    public com.doodod.staffmanagement.message.Company.Location getLocation(int index) {
      return location_.get(index);
    }
    /**
     * <code>repeated .doododmsg.Location location = 2;</code>
     *
     * <pre>
     * 员工位置 
     * </pre>
     */
    public com.doodod.staffmanagement.message.Company.LocationOrBuilder getLocationOrBuilder(
        int index) {
      return location_.get(index);
    }

    // optional .doododmsg.UserType user_type = 3;
    public static final int USER_TYPE_FIELD_NUMBER = 3;
    private com.doodod.staffmanagement.message.Company.UserType userType_;
    /**
     * <code>optional .doododmsg.UserType user_type = 3;</code>
     *
     * <pre>
     * 员工类型  
     * </pre>
     */
    public boolean hasUserType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .doododmsg.UserType user_type = 3;</code>
     *
     * <pre>
     * 员工类型  
     * </pre>
     */
    public com.doodod.staffmanagement.message.Company.UserType getUserType() {
      return userType_;
    }

    // optional bytes company = 4;
    public static final int COMPANY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString company_;
    /**
     * <code>optional bytes company = 4;</code>
     *
     * <pre>
     * 员工公司
     * </pre>
     */
    public boolean hasCompany() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes company = 4;</code>
     *
     * <pre>
     * 员工公司
     * </pre>
     */
    public com.google.protobuf.ByteString getCompany() {
      return company_;
    }

    private void initFields() {
      phoneMac_ = com.google.protobuf.ByteString.EMPTY;
      location_ = java.util.Collections.emptyList();
      userType_ = com.doodod.staffmanagement.message.Company.UserType.PASSENGER;
      company_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, phoneMac_);
      }
      for (int i = 0; i < location_.size(); i++) {
        output.writeMessage(2, location_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(3, userType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, company_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, phoneMac_);
      }
      for (int i = 0; i < location_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, location_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, userType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, company_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.doodod.staffmanagement.message.Company.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doodod.staffmanagement.message.Company.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.doodod.staffmanagement.message.Company.Employee prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code doododmsg.Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.doodod.staffmanagement.message.Company.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Employee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.doodod.staffmanagement.message.Company.Employee.class, com.doodod.staffmanagement.message.Company.Employee.Builder.class);
      }

      // Construct using com.doodod.staffmanagement.message.Company.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        phoneMac_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (locationBuilder_ == null) {
          location_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          locationBuilder_.clear();
        }
        userType_ = com.doodod.staffmanagement.message.Company.UserType.PASSENGER;
        bitField0_ = (bitField0_ & ~0x00000004);
        company_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Employee_descriptor;
      }

      public com.doodod.staffmanagement.message.Company.Employee getDefaultInstanceForType() {
        return com.doodod.staffmanagement.message.Company.Employee.getDefaultInstance();
      }

      public com.doodod.staffmanagement.message.Company.Employee build() {
        com.doodod.staffmanagement.message.Company.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.doodod.staffmanagement.message.Company.Employee buildPartial() {
        com.doodod.staffmanagement.message.Company.Employee result = new com.doodod.staffmanagement.message.Company.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.phoneMac_ = phoneMac_;
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            location_ = java.util.Collections.unmodifiableList(location_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userType_ = userType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.company_ = company_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.doodod.staffmanagement.message.Company.Employee) {
          return mergeFrom((com.doodod.staffmanagement.message.Company.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.doodod.staffmanagement.message.Company.Employee other) {
        if (other == com.doodod.staffmanagement.message.Company.Employee.getDefaultInstance()) return this;
        if (other.hasPhoneMac()) {
          setPhoneMac(other.getPhoneMac());
        }
        if (locationBuilder_ == null) {
          if (!other.location_.isEmpty()) {
            if (location_.isEmpty()) {
              location_ = other.location_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLocationIsMutable();
              location_.addAll(other.location_);
            }
            onChanged();
          }
        } else {
          if (!other.location_.isEmpty()) {
            if (locationBuilder_.isEmpty()) {
              locationBuilder_.dispose();
              locationBuilder_ = null;
              location_ = other.location_;
              bitField0_ = (bitField0_ & ~0x00000002);
              locationBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLocationFieldBuilder() : null;
            } else {
              locationBuilder_.addAllMessages(other.location_);
            }
          }
        }
        if (other.hasUserType()) {
          setUserType(other.getUserType());
        }
        if (other.hasCompany()) {
          setCompany(other.getCompany());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.doodod.staffmanagement.message.Company.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.doodod.staffmanagement.message.Company.Employee) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes phone_mac = 1;
      private com.google.protobuf.ByteString phoneMac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes phone_mac = 1;</code>
       *
       * <pre>
       * 员工手机mac地址
       * </pre>
       */
      public boolean hasPhoneMac() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes phone_mac = 1;</code>
       *
       * <pre>
       * 员工手机mac地址
       * </pre>
       */
      public com.google.protobuf.ByteString getPhoneMac() {
        return phoneMac_;
      }
      /**
       * <code>optional bytes phone_mac = 1;</code>
       *
       * <pre>
       * 员工手机mac地址
       * </pre>
       */
      public Builder setPhoneMac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phoneMac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes phone_mac = 1;</code>
       *
       * <pre>
       * 员工手机mac地址
       * </pre>
       */
      public Builder clearPhoneMac() {
        bitField0_ = (bitField0_ & ~0x00000001);
        phoneMac_ = getDefaultInstance().getPhoneMac();
        onChanged();
        return this;
      }

      // repeated .doododmsg.Location location = 2;
      private java.util.List<com.doodod.staffmanagement.message.Company.Location> location_ =
        java.util.Collections.emptyList();
      private void ensureLocationIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          location_ = new java.util.ArrayList<com.doodod.staffmanagement.message.Company.Location>(location_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.doodod.staffmanagement.message.Company.Location, com.doodod.staffmanagement.message.Company.Location.Builder, com.doodod.staffmanagement.message.Company.LocationOrBuilder> locationBuilder_;

      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public java.util.List<com.doodod.staffmanagement.message.Company.Location> getLocationList() {
        if (locationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(location_);
        } else {
          return locationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public int getLocationCount() {
        if (locationBuilder_ == null) {
          return location_.size();
        } else {
          return locationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public com.doodod.staffmanagement.message.Company.Location getLocation(int index) {
        if (locationBuilder_ == null) {
          return location_.get(index);
        } else {
          return locationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder setLocation(
          int index, com.doodod.staffmanagement.message.Company.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationIsMutable();
          location_.set(index, value);
          onChanged();
        } else {
          locationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder setLocation(
          int index, com.doodod.staffmanagement.message.Company.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          location_.set(index, builderForValue.build());
          onChanged();
        } else {
          locationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder addLocation(com.doodod.staffmanagement.message.Company.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationIsMutable();
          location_.add(value);
          onChanged();
        } else {
          locationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder addLocation(
          int index, com.doodod.staffmanagement.message.Company.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationIsMutable();
          location_.add(index, value);
          onChanged();
        } else {
          locationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder addLocation(
          com.doodod.staffmanagement.message.Company.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          location_.add(builderForValue.build());
          onChanged();
        } else {
          locationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder addLocation(
          int index, com.doodod.staffmanagement.message.Company.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          location_.add(index, builderForValue.build());
          onChanged();
        } else {
          locationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder addAllLocation(
          java.lang.Iterable<? extends com.doodod.staffmanagement.message.Company.Location> values) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          super.addAll(values, location_);
          onChanged();
        } else {
          locationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          locationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public Builder removeLocation(int index) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          location_.remove(index);
          onChanged();
        } else {
          locationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public com.doodod.staffmanagement.message.Company.Location.Builder getLocationBuilder(
          int index) {
        return getLocationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public com.doodod.staffmanagement.message.Company.LocationOrBuilder getLocationOrBuilder(
          int index) {
        if (locationBuilder_ == null) {
          return location_.get(index);  } else {
          return locationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public java.util.List<? extends com.doodod.staffmanagement.message.Company.LocationOrBuilder> 
           getLocationOrBuilderList() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(location_);
        }
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public com.doodod.staffmanagement.message.Company.Location.Builder addLocationBuilder() {
        return getLocationFieldBuilder().addBuilder(
            com.doodod.staffmanagement.message.Company.Location.getDefaultInstance());
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public com.doodod.staffmanagement.message.Company.Location.Builder addLocationBuilder(
          int index) {
        return getLocationFieldBuilder().addBuilder(
            index, com.doodod.staffmanagement.message.Company.Location.getDefaultInstance());
      }
      /**
       * <code>repeated .doododmsg.Location location = 2;</code>
       *
       * <pre>
       * 员工位置 
       * </pre>
       */
      public java.util.List<com.doodod.staffmanagement.message.Company.Location.Builder> 
           getLocationBuilderList() {
        return getLocationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.doodod.staffmanagement.message.Company.Location, com.doodod.staffmanagement.message.Company.Location.Builder, com.doodod.staffmanagement.message.Company.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.doodod.staffmanagement.message.Company.Location, com.doodod.staffmanagement.message.Company.Location.Builder, com.doodod.staffmanagement.message.Company.LocationOrBuilder>(
                  location_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      // optional .doododmsg.UserType user_type = 3;
      private com.doodod.staffmanagement.message.Company.UserType userType_ = com.doodod.staffmanagement.message.Company.UserType.PASSENGER;
      /**
       * <code>optional .doododmsg.UserType user_type = 3;</code>
       *
       * <pre>
       * 员工类型  
       * </pre>
       */
      public boolean hasUserType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .doododmsg.UserType user_type = 3;</code>
       *
       * <pre>
       * 员工类型  
       * </pre>
       */
      public com.doodod.staffmanagement.message.Company.UserType getUserType() {
        return userType_;
      }
      /**
       * <code>optional .doododmsg.UserType user_type = 3;</code>
       *
       * <pre>
       * 员工类型  
       * </pre>
       */
      public Builder setUserType(com.doodod.staffmanagement.message.Company.UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .doododmsg.UserType user_type = 3;</code>
       *
       * <pre>
       * 员工类型  
       * </pre>
       */
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userType_ = com.doodod.staffmanagement.message.Company.UserType.PASSENGER;
        onChanged();
        return this;
      }

      // optional bytes company = 4;
      private com.google.protobuf.ByteString company_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes company = 4;</code>
       *
       * <pre>
       * 员工公司
       * </pre>
       */
      public boolean hasCompany() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes company = 4;</code>
       *
       * <pre>
       * 员工公司
       * </pre>
       */
      public com.google.protobuf.ByteString getCompany() {
        return company_;
      }
      /**
       * <code>optional bytes company = 4;</code>
       *
       * <pre>
       * 员工公司
       * </pre>
       */
      public Builder setCompany(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes company = 4;</code>
       *
       * <pre>
       * 员工公司
       * </pre>
       */
      public Builder clearCompany() {
        bitField0_ = (bitField0_ & ~0x00000008);
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:doododmsg.Employee)
    }

    static {
      defaultInstance = new Employee(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:doododmsg.Employee)
  }

  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint64 planar_graph = 1;
    /**
     * <code>optional uint64 planar_graph = 1;</code>
     *
     * <pre>
     * 楼层id
     * </pre>
     */
    boolean hasPlanarGraph();
    /**
     * <code>optional uint64 planar_graph = 1;</code>
     *
     * <pre>
     * 楼层id
     * </pre>
     */
    long getPlanarGraph();

    // optional double location_x = 2;
    /**
     * <code>optional double location_x = 2;</code>
     *
     * <pre>
     * 坐标x
     * </pre>
     */
    boolean hasLocationX();
    /**
     * <code>optional double location_x = 2;</code>
     *
     * <pre>
     * 坐标x
     * </pre>
     */
    double getLocationX();

    // optional double location_y = 3;
    /**
     * <code>optional double location_y = 3;</code>
     *
     * <pre>
     * 坐标y
     * </pre>
     */
    boolean hasLocationY();
    /**
     * <code>optional double location_y = 3;</code>
     *
     * <pre>
     * 坐标y
     * </pre>
     */
    double getLocationY();

    // repeated uint64 time_stamp = 4;
    /**
     * <code>repeated uint64 time_stamp = 4;</code>
     *
     * <pre>
     * hbase记录的时间戳
     * </pre>
     */
    java.util.List<java.lang.Long> getTimeStampList();
    /**
     * <code>repeated uint64 time_stamp = 4;</code>
     *
     * <pre>
     * hbase记录的时间戳
     * </pre>
     */
    int getTimeStampCount();
    /**
     * <code>repeated uint64 time_stamp = 4;</code>
     *
     * <pre>
     * hbase记录的时间戳
     * </pre>
     */
    long getTimeStamp(int index);

    // repeated uint64 client_time = 5;
    /**
     * <code>repeated uint64 client_time = 5;</code>
     *
     * <pre>
     * 设备记录的时间戳
     * </pre>
     */
    java.util.List<java.lang.Long> getClientTimeList();
    /**
     * <code>repeated uint64 client_time = 5;</code>
     *
     * <pre>
     * 设备记录的时间戳
     * </pre>
     */
    int getClientTimeCount();
    /**
     * <code>repeated uint64 client_time = 5;</code>
     *
     * <pre>
     * 设备记录的时间戳
     * </pre>
     */
    long getClientTime(int index);

    // optional bytes position_sys = 6;
    /**
     * <code>optional bytes position_sys = 6;</code>
     *
     * <pre>
     * 定位引擎
     * </pre>
     */
    boolean hasPositionSys();
    /**
     * <code>optional bytes position_sys = 6;</code>
     *
     * <pre>
     * 定位引擎
     * </pre>
     */
    com.google.protobuf.ByteString getPositionSys();

    // optional bytes area = 7;
    /**
     * <code>optional bytes area = 7;</code>
     *
     * <pre>
     * 区域信息 
     * </pre>
     */
    boolean hasArea();
    /**
     * <code>optional bytes area = 7;</code>
     *
     * <pre>
     * 区域信息 
     * </pre>
     */
    com.google.protobuf.ByteString getArea();
  }
  /**
   * Protobuf type {@code doododmsg.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              planarGraph_ = input.readUInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              locationX_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              locationY_ = input.readDouble();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                timeStamp_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              timeStamp_.add(input.readUInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                timeStamp_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                timeStamp_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                clientTime_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              clientTime_.add(input.readUInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                clientTime_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                clientTime_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              bitField0_ |= 0x00000008;
              positionSys_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000010;
              area_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          timeStamp_ = java.util.Collections.unmodifiableList(timeStamp_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          clientTime_ = java.util.Collections.unmodifiableList(clientTime_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.doodod.staffmanagement.message.Company.Location.class, com.doodod.staffmanagement.message.Company.Location.Builder.class);
    }

    public static com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint64 planar_graph = 1;
    public static final int PLANAR_GRAPH_FIELD_NUMBER = 1;
    private long planarGraph_;
    /**
     * <code>optional uint64 planar_graph = 1;</code>
     *
     * <pre>
     * 楼层id
     * </pre>
     */
    public boolean hasPlanarGraph() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 planar_graph = 1;</code>
     *
     * <pre>
     * 楼层id
     * </pre>
     */
    public long getPlanarGraph() {
      return planarGraph_;
    }

    // optional double location_x = 2;
    public static final int LOCATION_X_FIELD_NUMBER = 2;
    private double locationX_;
    /**
     * <code>optional double location_x = 2;</code>
     *
     * <pre>
     * 坐标x
     * </pre>
     */
    public boolean hasLocationX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double location_x = 2;</code>
     *
     * <pre>
     * 坐标x
     * </pre>
     */
    public double getLocationX() {
      return locationX_;
    }

    // optional double location_y = 3;
    public static final int LOCATION_Y_FIELD_NUMBER = 3;
    private double locationY_;
    /**
     * <code>optional double location_y = 3;</code>
     *
     * <pre>
     * 坐标y
     * </pre>
     */
    public boolean hasLocationY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double location_y = 3;</code>
     *
     * <pre>
     * 坐标y
     * </pre>
     */
    public double getLocationY() {
      return locationY_;
    }

    // repeated uint64 time_stamp = 4;
    public static final int TIME_STAMP_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Long> timeStamp_;
    /**
     * <code>repeated uint64 time_stamp = 4;</code>
     *
     * <pre>
     * hbase记录的时间戳
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getTimeStampList() {
      return timeStamp_;
    }
    /**
     * <code>repeated uint64 time_stamp = 4;</code>
     *
     * <pre>
     * hbase记录的时间戳
     * </pre>
     */
    public int getTimeStampCount() {
      return timeStamp_.size();
    }
    /**
     * <code>repeated uint64 time_stamp = 4;</code>
     *
     * <pre>
     * hbase记录的时间戳
     * </pre>
     */
    public long getTimeStamp(int index) {
      return timeStamp_.get(index);
    }

    // repeated uint64 client_time = 5;
    public static final int CLIENT_TIME_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> clientTime_;
    /**
     * <code>repeated uint64 client_time = 5;</code>
     *
     * <pre>
     * 设备记录的时间戳
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getClientTimeList() {
      return clientTime_;
    }
    /**
     * <code>repeated uint64 client_time = 5;</code>
     *
     * <pre>
     * 设备记录的时间戳
     * </pre>
     */
    public int getClientTimeCount() {
      return clientTime_.size();
    }
    /**
     * <code>repeated uint64 client_time = 5;</code>
     *
     * <pre>
     * 设备记录的时间戳
     * </pre>
     */
    public long getClientTime(int index) {
      return clientTime_.get(index);
    }

    // optional bytes position_sys = 6;
    public static final int POSITION_SYS_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString positionSys_;
    /**
     * <code>optional bytes position_sys = 6;</code>
     *
     * <pre>
     * 定位引擎
     * </pre>
     */
    public boolean hasPositionSys() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes position_sys = 6;</code>
     *
     * <pre>
     * 定位引擎
     * </pre>
     */
    public com.google.protobuf.ByteString getPositionSys() {
      return positionSys_;
    }

    // optional bytes area = 7;
    public static final int AREA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString area_;
    /**
     * <code>optional bytes area = 7;</code>
     *
     * <pre>
     * 区域信息 
     * </pre>
     */
    public boolean hasArea() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes area = 7;</code>
     *
     * <pre>
     * 区域信息 
     * </pre>
     */
    public com.google.protobuf.ByteString getArea() {
      return area_;
    }

    private void initFields() {
      planarGraph_ = 0L;
      locationX_ = 0D;
      locationY_ = 0D;
      timeStamp_ = java.util.Collections.emptyList();
      clientTime_ = java.util.Collections.emptyList();
      positionSys_ = com.google.protobuf.ByteString.EMPTY;
      area_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, planarGraph_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, locationX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, locationY_);
      }
      for (int i = 0; i < timeStamp_.size(); i++) {
        output.writeUInt64(4, timeStamp_.get(i));
      }
      for (int i = 0; i < clientTime_.size(); i++) {
        output.writeUInt64(5, clientTime_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(6, positionSys_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(7, area_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, planarGraph_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, locationX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, locationY_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < timeStamp_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(timeStamp_.get(i));
        }
        size += dataSize;
        size += 1 * getTimeStampList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < clientTime_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(clientTime_.get(i));
        }
        size += dataSize;
        size += 1 * getClientTimeList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, positionSys_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, area_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.doodod.staffmanagement.message.Company.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doodod.staffmanagement.message.Company.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.doodod.staffmanagement.message.Company.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code doododmsg.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.doodod.staffmanagement.message.Company.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.doodod.staffmanagement.message.Company.Location.class, com.doodod.staffmanagement.message.Company.Location.Builder.class);
      }

      // Construct using com.doodod.staffmanagement.message.Company.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        planarGraph_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        locationX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        locationY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStamp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        clientTime_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        positionSys_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        area_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.doodod.staffmanagement.message.Company.internal_static_doododmsg_Location_descriptor;
      }

      public com.doodod.staffmanagement.message.Company.Location getDefaultInstanceForType() {
        return com.doodod.staffmanagement.message.Company.Location.getDefaultInstance();
      }

      public com.doodod.staffmanagement.message.Company.Location build() {
        com.doodod.staffmanagement.message.Company.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.doodod.staffmanagement.message.Company.Location buildPartial() {
        com.doodod.staffmanagement.message.Company.Location result = new com.doodod.staffmanagement.message.Company.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.planarGraph_ = planarGraph_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.locationX_ = locationX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.locationY_ = locationY_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          timeStamp_ = java.util.Collections.unmodifiableList(timeStamp_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.timeStamp_ = timeStamp_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          clientTime_ = java.util.Collections.unmodifiableList(clientTime_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.clientTime_ = clientTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.positionSys_ = positionSys_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.area_ = area_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.doodod.staffmanagement.message.Company.Location) {
          return mergeFrom((com.doodod.staffmanagement.message.Company.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.doodod.staffmanagement.message.Company.Location other) {
        if (other == com.doodod.staffmanagement.message.Company.Location.getDefaultInstance()) return this;
        if (other.hasPlanarGraph()) {
          setPlanarGraph(other.getPlanarGraph());
        }
        if (other.hasLocationX()) {
          setLocationX(other.getLocationX());
        }
        if (other.hasLocationY()) {
          setLocationY(other.getLocationY());
        }
        if (!other.timeStamp_.isEmpty()) {
          if (timeStamp_.isEmpty()) {
            timeStamp_ = other.timeStamp_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTimeStampIsMutable();
            timeStamp_.addAll(other.timeStamp_);
          }
          onChanged();
        }
        if (!other.clientTime_.isEmpty()) {
          if (clientTime_.isEmpty()) {
            clientTime_ = other.clientTime_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureClientTimeIsMutable();
            clientTime_.addAll(other.clientTime_);
          }
          onChanged();
        }
        if (other.hasPositionSys()) {
          setPositionSys(other.getPositionSys());
        }
        if (other.hasArea()) {
          setArea(other.getArea());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.doodod.staffmanagement.message.Company.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.doodod.staffmanagement.message.Company.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint64 planar_graph = 1;
      private long planarGraph_ ;
      /**
       * <code>optional uint64 planar_graph = 1;</code>
       *
       * <pre>
       * 楼层id
       * </pre>
       */
      public boolean hasPlanarGraph() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 planar_graph = 1;</code>
       *
       * <pre>
       * 楼层id
       * </pre>
       */
      public long getPlanarGraph() {
        return planarGraph_;
      }
      /**
       * <code>optional uint64 planar_graph = 1;</code>
       *
       * <pre>
       * 楼层id
       * </pre>
       */
      public Builder setPlanarGraph(long value) {
        bitField0_ |= 0x00000001;
        planarGraph_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 planar_graph = 1;</code>
       *
       * <pre>
       * 楼层id
       * </pre>
       */
      public Builder clearPlanarGraph() {
        bitField0_ = (bitField0_ & ~0x00000001);
        planarGraph_ = 0L;
        onChanged();
        return this;
      }

      // optional double location_x = 2;
      private double locationX_ ;
      /**
       * <code>optional double location_x = 2;</code>
       *
       * <pre>
       * 坐标x
       * </pre>
       */
      public boolean hasLocationX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double location_x = 2;</code>
       *
       * <pre>
       * 坐标x
       * </pre>
       */
      public double getLocationX() {
        return locationX_;
      }
      /**
       * <code>optional double location_x = 2;</code>
       *
       * <pre>
       * 坐标x
       * </pre>
       */
      public Builder setLocationX(double value) {
        bitField0_ |= 0x00000002;
        locationX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double location_x = 2;</code>
       *
       * <pre>
       * 坐标x
       * </pre>
       */
      public Builder clearLocationX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        locationX_ = 0D;
        onChanged();
        return this;
      }

      // optional double location_y = 3;
      private double locationY_ ;
      /**
       * <code>optional double location_y = 3;</code>
       *
       * <pre>
       * 坐标y
       * </pre>
       */
      public boolean hasLocationY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double location_y = 3;</code>
       *
       * <pre>
       * 坐标y
       * </pre>
       */
      public double getLocationY() {
        return locationY_;
      }
      /**
       * <code>optional double location_y = 3;</code>
       *
       * <pre>
       * 坐标y
       * </pre>
       */
      public Builder setLocationY(double value) {
        bitField0_ |= 0x00000004;
        locationY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double location_y = 3;</code>
       *
       * <pre>
       * 坐标y
       * </pre>
       */
      public Builder clearLocationY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        locationY_ = 0D;
        onChanged();
        return this;
      }

      // repeated uint64 time_stamp = 4;
      private java.util.List<java.lang.Long> timeStamp_ = java.util.Collections.emptyList();
      private void ensureTimeStampIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          timeStamp_ = new java.util.ArrayList<java.lang.Long>(timeStamp_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated uint64 time_stamp = 4;</code>
       *
       * <pre>
       * hbase记录的时间戳
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getTimeStampList() {
        return java.util.Collections.unmodifiableList(timeStamp_);
      }
      /**
       * <code>repeated uint64 time_stamp = 4;</code>
       *
       * <pre>
       * hbase记录的时间戳
       * </pre>
       */
      public int getTimeStampCount() {
        return timeStamp_.size();
      }
      /**
       * <code>repeated uint64 time_stamp = 4;</code>
       *
       * <pre>
       * hbase记录的时间戳
       * </pre>
       */
      public long getTimeStamp(int index) {
        return timeStamp_.get(index);
      }
      /**
       * <code>repeated uint64 time_stamp = 4;</code>
       *
       * <pre>
       * hbase记录的时间戳
       * </pre>
       */
      public Builder setTimeStamp(
          int index, long value) {
        ensureTimeStampIsMutable();
        timeStamp_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 time_stamp = 4;</code>
       *
       * <pre>
       * hbase记录的时间戳
       * </pre>
       */
      public Builder addTimeStamp(long value) {
        ensureTimeStampIsMutable();
        timeStamp_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 time_stamp = 4;</code>
       *
       * <pre>
       * hbase记录的时间戳
       * </pre>
       */
      public Builder addAllTimeStamp(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureTimeStampIsMutable();
        super.addAll(values, timeStamp_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 time_stamp = 4;</code>
       *
       * <pre>
       * hbase记录的时间戳
       * </pre>
       */
      public Builder clearTimeStamp() {
        timeStamp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // repeated uint64 client_time = 5;
      private java.util.List<java.lang.Long> clientTime_ = java.util.Collections.emptyList();
      private void ensureClientTimeIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          clientTime_ = new java.util.ArrayList<java.lang.Long>(clientTime_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated uint64 client_time = 5;</code>
       *
       * <pre>
       * 设备记录的时间戳
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getClientTimeList() {
        return java.util.Collections.unmodifiableList(clientTime_);
      }
      /**
       * <code>repeated uint64 client_time = 5;</code>
       *
       * <pre>
       * 设备记录的时间戳
       * </pre>
       */
      public int getClientTimeCount() {
        return clientTime_.size();
      }
      /**
       * <code>repeated uint64 client_time = 5;</code>
       *
       * <pre>
       * 设备记录的时间戳
       * </pre>
       */
      public long getClientTime(int index) {
        return clientTime_.get(index);
      }
      /**
       * <code>repeated uint64 client_time = 5;</code>
       *
       * <pre>
       * 设备记录的时间戳
       * </pre>
       */
      public Builder setClientTime(
          int index, long value) {
        ensureClientTimeIsMutable();
        clientTime_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 client_time = 5;</code>
       *
       * <pre>
       * 设备记录的时间戳
       * </pre>
       */
      public Builder addClientTime(long value) {
        ensureClientTimeIsMutable();
        clientTime_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 client_time = 5;</code>
       *
       * <pre>
       * 设备记录的时间戳
       * </pre>
       */
      public Builder addAllClientTime(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureClientTimeIsMutable();
        super.addAll(values, clientTime_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 client_time = 5;</code>
       *
       * <pre>
       * 设备记录的时间戳
       * </pre>
       */
      public Builder clearClientTime() {
        clientTime_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // optional bytes position_sys = 6;
      private com.google.protobuf.ByteString positionSys_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes position_sys = 6;</code>
       *
       * <pre>
       * 定位引擎
       * </pre>
       */
      public boolean hasPositionSys() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes position_sys = 6;</code>
       *
       * <pre>
       * 定位引擎
       * </pre>
       */
      public com.google.protobuf.ByteString getPositionSys() {
        return positionSys_;
      }
      /**
       * <code>optional bytes position_sys = 6;</code>
       *
       * <pre>
       * 定位引擎
       * </pre>
       */
      public Builder setPositionSys(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        positionSys_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes position_sys = 6;</code>
       *
       * <pre>
       * 定位引擎
       * </pre>
       */
      public Builder clearPositionSys() {
        bitField0_ = (bitField0_ & ~0x00000020);
        positionSys_ = getDefaultInstance().getPositionSys();
        onChanged();
        return this;
      }

      // optional bytes area = 7;
      private com.google.protobuf.ByteString area_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes area = 7;</code>
       *
       * <pre>
       * 区域信息 
       * </pre>
       */
      public boolean hasArea() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes area = 7;</code>
       *
       * <pre>
       * 区域信息 
       * </pre>
       */
      public com.google.protobuf.ByteString getArea() {
        return area_;
      }
      /**
       * <code>optional bytes area = 7;</code>
       *
       * <pre>
       * 区域信息 
       * </pre>
       */
      public Builder setArea(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        area_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes area = 7;</code>
       *
       * <pre>
       * 区域信息 
       * </pre>
       */
      public Builder clearArea() {
        bitField0_ = (bitField0_ & ~0x00000040);
        area_ = getDefaultInstance().getArea();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:doododmsg.Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:doododmsg.Location)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_doododmsg_Employee_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doododmsg_Employee_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_doododmsg_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doododmsg_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcompany.proto\022\tdoododmsg\"}\n\010Employee\022\021" +
      "\n\tphone_mac\030\001 \001(\014\022%\n\010location\030\002 \003(\0132\023.do" +
      "ododmsg.Location\022&\n\tuser_type\030\003 \001(\0162\023.do" +
      "ododmsg.UserType\022\017\n\007company\030\004 \001(\014\"\225\001\n\010Lo" +
      "cation\022\024\n\014planar_graph\030\001 \001(\004\022\022\n\nlocation" +
      "_x\030\002 \001(\001\022\022\n\nlocation_y\030\003 \001(\001\022\022\n\ntime_sta" +
      "mp\030\004 \003(\004\022\023\n\013client_time\030\005 \003(\004\022\024\n\014positio" +
      "n_sys\030\006 \001(\014\022\014\n\004area\030\007 \001(\014*A\n\010UserType\022\r\n" +
      "\tPASSENGER\020\000\022\014\n\010EMPLOYEE\020\001\022\013\n\007MACHINE\020\002\022" +
      "\013\n\007OUTDOOR\020\003B$\n\"com.doodod.staffmanageme",
      "nt.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_doododmsg_Employee_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_doododmsg_Employee_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_doododmsg_Employee_descriptor,
              new java.lang.String[] { "PhoneMac", "Location", "UserType", "Company", });
          internal_static_doododmsg_Location_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_doododmsg_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_doododmsg_Location_descriptor,
              new java.lang.String[] { "PlanarGraph", "LocationX", "LocationY", "TimeStamp", "ClientTime", "PositionSys", "Area", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
